---
name: Docker build & scan

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and scan image
        uses: ISID/build-and-scan-image@v0.2.0
        with:
          tag: "ahinko/simple-pg-backup:${{ github.sha }}"
          path: "."
