---
name: Meta - Sync labels

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - ".github/labels.yaml"

jobs:
  labels:
    name: Sync Labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Sync Labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
